### ISSUE TITLE
SRB2 all models but vanilla or some vanilla models won't load

### ISSUE THREAD

**Issue by shaweek13** [SRB2-Mobile/SRB2-Android#29]
anyway to fix this ?

**Comment by xsm2** [comment]
You have to use the new models pack feature to change models. The instructions of how to do it are in the patch notes of the [2.2.11 release](https://github.com/SRB2-Mobile/SRB2-Android/releases/tag/android-port-build-v2211). 

That said, the models pack do not work for me and I already opened an issue about that  (#26). Be specially carefull when writing the command because there is a bug when you write the name of a file that doesn't exist, the game stops using the default model pack which means you can't use models unless you change the model pack, but as I said, at least for me the feature is bugged and I can't change model packs which means I'm stuck without even the default models.

**Comment by shaweek13** [comment]
thanks
